### ISSUE TITLE
How to buy products in China?

### ISSUE THREAD

**Issue by modi12jin** [Makerfabs/Project_Touch-Screen-Camera#1]
Ask about non-technical topics, how can China buy your products?

**Comment by Makerfabs** [comment]
Please contact sales: zeqing2012@makerfabs.com

 

发件人: modi12jin [mailto:notifications@github.com] 
发送时间: 2020年11月9日 19:23
收件人: Makerfabs/Project_Touch-Screen-Camera
抄送: Subscribed
主题: [Makerfabs/Project_Touch-Screen-Camera] How to buy products in China? (#1)

 

Ask about non-technical topics, how can China buy your products?
