### ISSUE TITLE
SCL and SDA pinout 

### ISSUE THREAD

**Issue by gigwegbe** [Makerfabs/Project_Touch-Screen-Camera#5]
Hello Makerfabs, 
I have been trying to interface with an accelerator(MPU-6050) and so far I can't identify the SCL and SDA pins on the board(ESP32 TFT capacitive screen). Please kindly specify them. Thanks.

**Comment by 195cn** [comment]
ESP32 can use any pins as I2C pins. Such like:

`Wire.begin(MAKEPYTHON_ESP32_SDA, MAKEPYTHON_ESP32_SCL);`
