### ISSUE TITLE
Detected camera not supported

### ISSUE THREAD

**Issue by citizenanalog** [Makerfabs/Project_Touch-Screen-Camera#9]
I'm running Camera_v2 and monitoring serial port after upload results in:

ILI9488 Test!
I2C device found at address 0x38  !
Card Mount Successed
SD init over.
TFT init over.
[E][camera.c:1113] camera_probe(): Detected camera not supported.
[E][camera.c:1379] esp_camera_init(): Camera probe failed with error 0x20004

Any suggestions?

**Comment by citizenanalog** [comment]
I'm guessing it's a bad camera module...

**Comment by 195cn** [comment]
Yes.
The camera is probably broken
If reinstalling the camera still results in this, it should be damaged.
The camera code was moved directly from the ESP-CAM project, and I'm not very familiar with the error.

**Comment by citizenanalog** [comment]
Thanks for the feedback!

**Comment by citizenanalog** [comment]
Tried a brand new camera and still getting the same error :(

**Comment by 195cn** [comment]
What is the version of your ESP32 library? 1.0.6 was used for development.
Versions later than 2.0 proved unable to load the SD library properly. There may be other problems.

**Comment by citizenanalog** [comment]
I'm using esp32 v 1.0.6

**Comment by citizenanalog** [comment]
Downgrade to esp32 v 1.0.4 and it works! Seems like an issue with the newer version for me anyway.
